// Public model surface. Keep this facade explicit: adding an export is adding a package promise.

export type {
  Area,
  Asset,
  Attrs,
  AttrValue,
  Azimuth,
  Boundary,
  BoundaryKind,
  Column,
  ColumnDecl,
  DrawnLine,
  Edge,
  GridAxis,
  GridRef,
  Level,
  Model,
  Opening,
  Pt,
  Rect,
  Seg,
  SiteOrigin,
  SitePolygon,
  Space,
  Zone,
} from "./core/model.js";

export {
  areaM2,
  DEFAULT_LANGUAGE_VERSION,
  displayName,
  effectiveAttr,
  EXTERIOR,
  heff,
  isCoveredAbove,
  isIndoor,
  isOutside,
  isSemiOutdoor,
  isVoid,
  KOYU_VERSION,
  koyuSince,
  levelsSorted,
  MURO_SUPPORT,
  NEWEST_LANGUAGE_VERSION,
  newUids,
  speaksMuro,
  SUPPORTED_LANGUAGE_VERSIONS,
  toCanonical,
  versionLine,
  zoneAreaM2,
} from "./core/model.js";
